# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['run.py'],
    pathex=['D:\\Github\\Truck_Opti'],
    binaries=[],
    datas=[
        ('app/templates', 'app/templates'),
        ('app/static', 'app/static'),
        ('app/data', 'app/data'),
        ('logs', 'logs'),
        ('app/intelligent_errors.db', 'app/'),
        ('app/truck_opti_errors.db', 'app/'),
    ],
    hiddenimports=[
        'app',
        'app.models',
        'app.routes', 
        'app.packer',
        'app.advanced_packer',
        'app.cost_engine',
        'app.ml_optimizer',
        'app.multi_order_optimizer',
        'app.route_optimizer',
        'app.websocket_manager',
        'werkzeug.security',
        'jinja2',
        'click',
        'itsdangerous',
        'markupsafe',
        'flask',
        'flask.helpers',
        'sqlalchemy',
        'sqlalchemy.dialects.sqlite',
        'pandas',
        'numpy',
        'py3dbp',
        'dataclasses',
        'sqlite3',
        'json',
        'datetime',
        'uuid',
        'webbrowser',
        'socket',
        'threading',
        'time',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Exclude problematic modules that aren't needed
        'matplotlib',
        'tkinter',
        'turtle', 
        'test',
        'tests',
        'unittest',
        'doctest',
        # Only exclude the most problematic numpy modules, keep core functionality
        'numpy.f2py',
        'numpy.testing',
        'numpy.distutils',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='TruckOpti_Working',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='app/static/truck_icon.ico' if os.path.exists('app/static/truck_icon.ico') else None,
)